eureka:
  defaultZone: http://localhost:7001/eureka
datasource:
  url: jdbc:mysql://localhost:3306/i_cloud?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useAffectedRows=true
  username: root
  password: ITwh@306
redis:
  host: localhost
  port: 6379
  password: