server:
  port: 7005
spring:
  application:
    name: i-cloud-config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configs
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    prefer-ip-address: true
