server:
  port: 7005
spring:
  application:
    name: i-cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/428064270/i-cloud-config
          search-paths: /
          default-label: main
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    prefer-ip-address: true
