eureka:
  defaultZone: http://124.71.128.218:7001/eureka
datasource:
  url: jdbc:mysql://124.71.128.218:3306/i_cloud?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useAffectedRows=true
  username: root
  password: root
redis:
  host: 124.71.128.218
  port: 6379
  password: ITwh@306